//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_binout_maponly_H
#define METASPRITE_binout_maponly_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_maponly_TILE_ORIGIN 0
#define binout_maponly_TILE_W 8
#define binout_maponly_TILE_H 8
#define binout_maponly_WIDTH 56
#define binout_maponly_HEIGHT 96
#define binout_maponly_TILE_COUNT 45
#define binout_maponly_PALETTE_COUNT 1
#define binout_maponly_COLORS_PER_PALETTE 4
#define binout_maponly_TOTAL_COLORS 4
#define binout_maponly_MAP_ATTRIBUTES 0
extern const unsigned char binout_maponly_map[84];
#define binout_maponly_map_attributes binout_maponly_map

BANKREF_EXTERN(binout_maponly)

extern const palette_color_t binout_maponly_palettes[4];

#endif
