//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_binout_maponly_nopal_H
#define METASPRITE_binout_maponly_nopal_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define binout_maponly_nopal_TILE_ORIGIN 0
#define binout_maponly_nopal_TILE_W 8
#define binout_maponly_nopal_TILE_H 8
#define binout_maponly_nopal_WIDTH 56
#define binout_maponly_nopal_HEIGHT 96
#define binout_maponly_nopal_TILE_COUNT 45
#define binout_maponly_nopal_MAP_ATTRIBUTES 0
extern const unsigned char binout_maponly_nopal_map[84];
#define binout_maponly_nopal_map_attributes binout_maponly_nopal_map

BANKREF_EXTERN(binout_maponly_nopal)


#endif
