//AUTOGENERATED FILE FROM png2asset
// Conversion args: /sushi_level07.png -c /zgb_sushi_level07.c -b 255 -map -noflip -pack_mode sms -bpp 4 -keep_palette_order -use_structs -keep_palette_order -rel_paths -keep_duplicate_tiles -source_tileset sushi_tiles.png -entity_tileset sushi_objects.png

#ifndef METASPRITE_zgb_sushi_level07_H
#define METASPRITE_zgb_sushi_level07_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_sushi_level07_tiles_info;
extern const struct MapInfo zgb_sushi_level07;

#endif
