//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_zgb_largemap_3_attribs_smsgg_H
#define METASPRITE_zgb_largemap_3_attribs_smsgg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_largemap_3_attribs_smsgg_tiles_info;
extern const struct MapInfo zgb_largemap_3_attribs_smsgg;

#endif
