//AUTOGENERATED FILE FROM png2asset
// Conversion args: /color_indexed_nums8x8_map_0_to_39.png -o /zgb_color_indexed_nums_map_3.c -map -use_map_attributes -keep_palette_order -use_structs -entity_tileset /color_indexed_nums8x8_30_to_39.png

#ifndef METASPRITE_zgb_color_indexed_nums_map_3_H
#define METASPRITE_zgb_color_indexed_nums_map_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_color_indexed_nums_map_3_tiles_info;
extern const struct MapInfo zgb_color_indexed_nums_map_3;

#endif
