//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /zgb_largemap_2.c -b 255 -map -use_structs -pack_mode sms -bpp 4 -keep_palette_order

#ifndef METASPRITE_zgb_largemap_2_H
#define METASPRITE_zgb_largemap_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_largemap_2_tiles_info;
extern const struct MapInfo zgb_largemap_2;

#endif
