//AUTOGENERATED FILE FROM png2asset
// Conversion args: /nums8x8_map_0_to_39.png -o /zgb_nums_map_8.c -map -use_structs -keep_duplicate_tiles -source_tileset /nums8x8_9_to_0.png -entity_tileset /nums8x8_30_to_39.png

#ifndef METASPRITE_zgb_nums_map_8_H
#define METASPRITE_zgb_nums_map_8_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_nums_map_8_tiles_info;
extern const struct MapInfo zgb_nums_map_8;

#endif
