//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /zgb_largemap_1.c -b 255 -map -use_structs -noflip

#ifndef METASPRITE_zgb_largemap_1_H
#define METASPRITE_zgb_largemap_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_largemap_1_tiles_info;
extern const struct MapInfo zgb_largemap_1;

#endif
