//AUTOGENERATED FILE FROM png2asset
// Conversion args: /largemap.png -c /zgb_largemap_3_attribs_smsgg.c -b 255 -map -use_structs -pack_mode sms -bpp 4 -keep_palette_order -use_map_attributes

#ifndef METASPRITE_zgb_largemap_3_attribs_smsgg_H
#define METASPRITE_zgb_largemap_3_attribs_smsgg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_largemap_3_attribs_smsgg_tiles_info;
extern const struct MapInfo zgb_largemap_3_attribs_smsgg;

#endif
