//AUTOGENERATED FILE FROM png2asset
// Conversion args: /sprite_slon.png -c /zgb_sprite_1.c -use_structs -b 255 -spr8x16 -px 0 -py 0 -pw 32 -ph 24 -sw 64 -sh 48

#ifndef METASPRITE_zgb_sprite_1_H
#define METASPRITE_zgb_sprite_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo zgb_sprite_1;

#endif
