//AUTOGENERATED FILE FROM png2asset
// Conversion args: /sgb_border.png -c /zgb_sgb_border_1.c -b 255 -map -bpp 4 -max_palettes 4 -use_map_attributes -use_structs -pack_mode sgb

#ifndef METASPRITE_zgb_sgb_border_1_H
#define METASPRITE_zgb_sgb_border_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "TilesInfo.h"
#include "MapInfo.h"

extern const struct TilesInfo zgb_sgb_border_1_tiles_info;
extern const struct MapInfo zgb_sgb_border_1;

#endif
